# .readthedocs.yaml -*- mode: YAML -*-
# https://blog.readthedocs.com/migrate-configuration-v2/
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: doot/_docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - mkdir -p .temp
      - asdf plugin add direnv
      - asdf install direnv
      - direnv allow
    create_environment:
      - direnv exec . uv venv
    install:
      - direnv exec . uv sync --group docs
    build:
      html:
        - echo "Building HTML"
        - >
          { direnv allow; 
          direnv exec .
          polyglot docs --sphinx;
          }
        - mkdir -p "$READTHEDOCS_OUTPUT/html"
        - mv .temp/docs/sphinx/* "$READTHEDOCS_OUTPUT/html"
