verbosity               = 2

[tool.doot]
announce_groups = false

[tool.doot.directories]
build = "build"
temp  = ".temp"

wheel = "build/wheel"

[tool.doot.group.pip]
debug = true
[tool.doot.group.python]
debug = true
[tool.doot.group.gtags]
[tool.doot.group.git]
