# -*- mode:toml; -*-
[startup]
doot_version         = "1.1.0"
loaders              = { commands="default", task="default", parser="default" }
sources              = { tasks=[".tasks"], code=[] }
sleep                = { task=0.2, subtask=1, batch=1 }
max_steps            = 100_000
skip_default_plugins = false
skip_plugin_search   = false
empty_cmd            = "list"
implicit_task_cmd    = "run"

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd"}

[shutdown]
notify           = { speak=false } # success_msg="", fail_msg=""
defaulted_values = { write=false, path=".defaulted_values.toml" }
exit_on_load_failures = false

[settings.commands]
[settings.commands.run]
tracker        = "default"
runner         = "default"
reporter       = "default"
report-line    = []
location_check = { make_missing=true, strict=true }

[settings.commands.list]
hide = []
aliases = { tasks=[], plugins=["--plugins"] }

[logging]
[logging.stream]
level = "user"
filter = []
target = "stdout"
format="{levelname:<8} : {message}"

[logging.file]
level        = "NOTSET"
filter       = ["jgdv"]
target       = "rotate"
format       = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})"
filename_fmt = "doot.log"

[logging.printer]
level        = "NOTSET"
colour       = true
target       = ["stdout", "rotate"]
format       = "{message}"
filename_fmt = "doot_printed.log"

[logging.subprinters]
default       = {level="user"}
cmd           = {level="user",  colour="cyan"}
task_header   = {level="user",  colour="magenta"}
task          = {level="user",  colour="white"}
action_exec   = {level="user",  colour="cyan"}

[logging.extra]

[[locations]]
tasks   = "protect::>.tasks"
src     = "protect::>doot"
temp    = "clean::>.temp"
logs    = "{temp}/logs"
build   = "{temp}/build"
