verbosity                = 2
default_tasks            =  ["locs::report"]
action_string_formatting = "new"

[plugins.command]
step = "doot.utils.step_cmd:StepCmd"

[tool.doot]
say-on-exit     = false
glob_ignores    = ['.git', '.DS_Store', "__pycache__"]
subtask-sleep   = 1
batch-sleep     = 1

[tool.doot.directories]
build    = "build"
temp     = ".temp"
lint-out = "build/lint"
wheel    = "build/wheel"

[tool.doot.group.pip]
debug = true
[tool.doot.group.python]
debug = true
[tool.doot.group.gtags]
[tool.doot.group.git]

[tool.doot.group.dot]
src = "."

[tool.doot.python.lint]
grouped = false
