# -*- mode:toml; -*-

[startup]
doot_version         = "1.1.0"
loaders              = { commands="default", task="default", parser="default" }
sources              = { tasks=[".tasks"], code=[] }

[shutdown]
notify                 = { speak=false } # success_msg="", fail_msg=""
defaulted_values       = { write=false, path=".defaulted_values.toml" }
exit_on_load_failures  = false

[settings.commands]

[settings.commands.run]
tracker        = "default"
runner         = "default"
reporter       = "default"
report-line    = []
location_check = { make_missing=true, strict=true }

[settings.commands.list]
hide = []
aliases = { tasks=[], plugins=["--plugins"] }

[logging]

[logging.stream]
level   = "WARNING"
filter  = []
target  = "stdout"
format  = "{levelname:<8}  : {message}"

[logging.file]
level        = "NOTSET"
filter       = ["jgdv"]
target       = "rotate"
format       = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})"
filename_fmt = "doot.log"

[logging.printer]
level        = "INFO"
colour       = true
target       = ["stdout", "rotate"]
format       = "{message}"
filename_fmt = "doot_printed.log"

[logging.extra]

[[locations]]
tasks   = "protect::>.tasks"
src     = "protect::>doot"
temp    = "clean::>.temp"
logs    = "{temp}/logs"
build   = "{temp}/build"
