verbosity                = 2
default_tasks            = ["locs::report"]
subtask                  = { sleep = 1 }
batch                    = { sleep = 1 }
notify                   = { say-on-exit = false }
loaders                  = {commands = "default", task = "default", parser = "default"}

[plugins]
# Allows for defining shorthands
command        = { other-run = "doot.cmds.run_cmd:RunCmd", tasks = "doot.cmds.list_cmd:ListCmd" }
report-line    = {}
reporter       = {}
action         = {}
tasker         = {}

[commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = []}

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[logging]
stream  = { level = "WARN", format  = "{levelname:<8} : {message}", filters = ["doot"] }
file    = { level = "DEBUG", format = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filters =  ["doot"] }
printer = { colour = true }

[[locations]]
tasks        = ".tasks"
temp         = ".temp"
src          = "doot"
build        = "build"
docs         = "docs"
data         = "data"
codegen      = "{src}/_codegen"
listings_out = "{build}/listing"
lint_out     = "{build}/lint"
