# towncrier.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
## https://towncrier.readthedocs.io/en/stable/configuration.html
[tool.towncrier]
name       = "doot"
version    = "0.1.1"
directory  = "doot/_docs/_changes"
filename   = "CHANGELOG.md"
template   = "doot/_docs/_templates/news.md"
create_add_extension = true
