X-machine        : 1 : x_machine
x_machine        : 1
x11              : 1
x_com            : 14
x_files          : 1
x_men            : 1
XAI              : 1
xanadu           : 1
xargs            : 1
xbox             : 10
xbox_live        : 2
xcom             : 2 : x_com
XCS              : 1
xenoanthropology : 1
xenocrypt        : 2
xenofeminism     : 1
xenophobia       : 11
xerox_parc       : 1
xfiles           : 1 : x_files
XFT              : 1
