# #  python-publish.yml -*- mode: YAML -*-

# Actions to build and upload to pypi
# Actions Used:
# https://github.com/astral-sh/setup-uv
# https://github.com/actions/checkout/
# https://github.com/actions/upload-artifact
# https://github.com/actions/download-artifact
# https://github.com/pypa/gh-action-pypi-publish

name: Run Tests

on:
  workflow_dispatch: 
  push:
    branches: [main]
    
permissions:
  contents: read

# --------------------------------------------------
jobs:
  test:
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4
      - name: setup polyglot
        run: |
          asdf plugin add direnv
          asdf install
          direnv allow
          direnv export gha >> "$GITHUB_ENV"
      - name: setup
        run: |
          uv venv
          uv sync --group test
      - name: test
        run: |
          uv run tox -e test

          
